### ISSUE TITLE
AppleHDA_ALC668 issues in 10.11.4

### ISSUE THREAD

**Issue by nuudles** [vbourachot/Dell-XPS13-9333-DSDT-Patch#1]
Hey @vbourachot! I've been having using your patch_hda to generate ALC668 drivers for my Dell XPS12 9Q33 for a while now to great success. Yesterday 10.11.4 was released, so I upgraded to it today and it looks like it no longer works. I thought it might be related to this thread:

http://www.tonymacx86.com/el-capitan-laptop-support/188853-fix-10-11-4-broken-audio-applehda-injector-dummyhda.html

But so far I haven't had any luck. Was wondering if you had any ideas?

**Comment by vbourachot** [comment]
Correct, the info.plist of the vanilla AppleHDA has changed in 10.11.4, so you need to recreate the injector kext after updating to 10.11.4. There's no changes required to the script, but you need to rerun it from 10.11.4.

If you're using the makefile in this repo, the following will recreate the injector and install it:

```
make clean
make patch_hda
sudo make install_hda

```

**Comment by nuudles** [comment]
Thanks for the quick response! I did actually re-run it in 10.11.4 after cleaning out the old kext, but still don't appear to have audio after replacing the kext with the new one and rebooting. Grepping /var/log/system.log I saw these messages:

```
Mar 22 10:30:31 nuudells kernel[0]: Sound assertion in AppleHDADriver at line 1601
Mar 22 10:30:31 nuudells kernel[0]: Sound assertion in AppleHDADriver at line 2275
Mar 22 10:30:31 nuudells kernel[0]: Sound assertion in AppleHDADriver at line 212
Mar 22 10:30:41 nuudells kernel[0]: Sound assertion in AppleHDADriver at line 3685
Mar 22 10:30:41 nuudells kernel[0]: Sound assertion in AppleHDADriver at line 1103
```

**Comment by vbourachot** [comment]
I wouldn't sweat these errors. You can actually see them even when sound is working (try to grep an older system.log from before you updated to 10.11.4, chances are you'll see assertions there too).

Try to rebuild your cache as per the instructions in the first post in the thread you linked above. It can get finicky to get the injector to kick in after reinstalling it. Also, try to shutdown after you rebuild your cache, instead of rebooting. It helps sometimes when the HDA chip gets stuck in a bad state across reboots.

On the bright side, I can guarantee you that it will work the way you're doing it.. I updated last night and restored sound after recreating the injector.

**Comment by nuudles** [comment]
Ahh, quite right! After rebuilding the cache again and shutting down, then starting it back up again I'm back in business! Thanks so much for your help!
